name: flutter_mdi_gui
description: "A Multi-Document Interface for Flutter."
version: 0.0.1
homepage: https://github.com/ibariens/flutter_mdi_gui
repository: https://github.com/ibariens/flutter_mdi_gui

environment:
  sdk: ^3.5.3
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
